[package]
name = "image_resizer_s3"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.24"
clap = { version = "4.0", features = ["derive", "env"] }
anyhow = "1.0"
serde_json = "1.0"


# WASM-specific configuration
[lib]
crate-type = ["cdylib"]
